#!/bin/sh
### BEGIN INIT INFO
# Provides:          homeassistant
# Required-Start:    $remote_fs $syslog $networking
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Plex Media Server
# Description:       homeassistant
# Author:            Cedric Quillevere / origin@killy.net
# Rewamped	     Christian Svedin / christian.svedin@gmail.com
# Version:           1.2
### END INIT INFO
case "$1" in
start)
hass
;;
stop)
 kill -9 $(pidof python)
;;
restart)
 kill -9 $(pidof python)& nohup hass&
esac
